services:
  db:
    image: mysql:8
    container_name: unifield_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin@1234
      MYSQL_DATABASE: unified_db
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: unifield_backend
    restart: always
    env_file:
      - ./backend/.env.docker
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: unifield_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
